# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.uRLLabel = QtWidgets.QLabel(self.centralwidget)
        self.uRLLabel.setObjectName("uRLLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.uRLLabel)
        self.ed_url = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_url.setObjectName("ed_url")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_url)
        self.lb_an = QtWidgets.QLabel(self.centralwidget)
        self.lb_an.setObjectName("lb_an")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_an)
        self.ed_css = QtWidgets.QLineEdit(self.centralwidget)
        self.ed_css.setObjectName("ed_css")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ed_css)
        self.verticalLayout.addLayout(self.formLayout)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_add = QtWidgets.QPushButton(self.centralwidget)
        self.bt_add.setObjectName("bt_add")
        self.horizontalLayout.addWidget(self.bt_add)
        self.bt_openWeb = QtWidgets.QPushButton(self.centralwidget)
        self.bt_openWeb.setObjectName("bt_openWeb")
        self.horizontalLayout.addWidget(self.bt_openWeb)
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout.addWidget(self.bt_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ed_log = QtWidgets.QTextEdit(self.centralwidget)
        self.ed_log.setObjectName("ed_log")
        self.verticalLayout.addWidget(self.ed_log)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uRLLabel.setText(_translate("MainWindow", "目标URL"))
        self.ed_url.setText(_translate("MainWindow", "https://www.vmall.com/product/10086726905036.html"))
        self.lb_an.setText(_translate("MainWindow", "目标按钮"))
        self.ed_css.setText(_translate("MainWindow", "#pro-operation > a:nth-child(2)"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">使用步骤:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.第一次使用请先点击[<span style=\" font-weight:600; color:#ff0000;\">增加账号cookies</span>]就是提前在网页中登录好账号,这个可以登入多个,会保存在cookies目录中</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.设置好账号后,就可以点击[<span style=\" font-weight:600; color:#ff0000;\">启动浏览器</span>],意思就是会同时运行cookies目录中所有提前设置好的账号</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.当浏览器都开启了之后,请自己把产品的尺寸,规格,型号等参数,网页上自己弄![]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.设置好一切后,点击[<span style=\" font-weight:600; color:#ff0000;\">全部开始按钮</span>]</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(假如你只有一个号,你可以多复制几次,就可以形成一个账号多个页面同时抢购)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">如果你要自定义别的产品:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第一种情况:还是华为mate40系列只是换成mate40 pro+ 或者保时捷,那就只需要把目标URL改了就好了,不用动目标按钮的文本</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第二种情况:就是干脆是别的网站的产品了(这种情况按钮肯定是会变的,所以请按照下方的步骤获取目标按钮的css选择器文本)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">获取目标按钮cs选择器文本方法:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1.打开你的网站然后在浏览器中找到你需要不断点击的按钮 按f12 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">https://attach.52pojie.cn//forum/202011/12/165648ml2jxid0bzflaz0f.gif?l</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ff007f;\">(有时候目标按钮的属性是动态的,所以最好是懂点css的基础,或者自己找规律来改)</span></p></body></html>"))
        self.bt_add.setText(_translate("MainWindow", "1.增加账号cookies"))
        self.bt_openWeb.setText(_translate("MainWindow", "2.启动浏览器"))
        self.bt_start.setText(_translate("MainWindow", "3.全部开始"))
